name = "compositor_discovery"
copyright = "Copyright © 2022 Aidan Prangnell"

[[interface]]
name = "wp_compositor_discovery"
summary = "Global object for discovering wayland subcompositors"
description = """
Subcompositors may run within a main wayland compositor providing various extra services atop the primary compositor.
For example, the notification system may be implemented by a subcompositor providing the notification protocol on another wayland socket whilst creating a window and showing notifications on the primary compositor.

When a compositor becomes available, or at global bind time, a set of available events specifying the global and path to compositor are sent. Multiple events per subcompositor path may be sent.
"""
version = 1

[[interface.request]]
name = "register"
summary = "Register an interface as available"

[[interface.request.arg]]
name = "global"
type = "string"
summary = "The wayland global provided by the subcompositor"

[[interface.request.arg]]
name = "path"
type = "array"
summary = "The path to the compositors socket"

[[interface.event]]
name = "available"
summary = "A subcompositor that can be connected to for additional functionality"

[[interface.event.arg]]
name = "global"
type = "string"
summary = "The wayland interface of a global provided by the subcompositor"

[[interface.event.arg]]
name = "path"
type = "array"
summary = "The path to the compositors socket"

